version: "3.9"
services:
  solar:
    image: ghcr.io/mrhumanrebel/solar_mining:latest
    container_name: solar_monitor
    restart: unless-stopped
    volumes:
      - ./state.json:/app/state.json
      - ./solarman_data.json:/app/solarman_data.json
      - ./quote_usage.json:/app/quote_usage.json
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
