version: "3.9"
services:
  solar:
    image: ghcr.io/mrhumanrebel/solar_mining:latest
    container_name: solar_monitor
    restart: unless-stopped
    environment:
      - MY_BOT_TOKEN=${MY_BOT_TOKEN}
      - MY_CHAT_ID=${MY_CHAT_ID}
      - MY_WEATHER_API=${MY_WEATHER_API}
      - MY_LOCATION_LAT=${MY_LOCATION_LAT}
      - MY_LOCATION_LON=${MY_LOCATION_LON}
      - MY_APP_ID=${MY_APP_ID}
      - MY_APP_SECRET=${MY_APP_SECRET}
      - MY_EMAIL=${MY_EMAIL}
      - MY_PASSWORD=${MY_PASSWORD}
      - MY_DEVICE_SN=${MY_DEVICE_SN}
      - MY_QUOTE_LIMIT=${MY_QUOTE_LIMIT}
      - MY_QUOTE_FILE=/app/quote_usage.json
      - MY_STATE_FILE=/app/state.json
      - MY_SOLARMAN_FILE=/app/solarman_data.json
    volumes:
      - ./state.json:/app/state.json
      - ./solarman_data.json:/app/solarman_data.json
      - ./quote_usage.json:/app/quote_usage.json
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
    networks:
      - backend
    dns:
      - 192.168.0.197
networks:
  backend:
    external: true